# Generated by Django 5.1.2 on 2024-12-10 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0003_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
    ]
