# Generated by Django 5.1.2 on 2024-12-11 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APIs', '0007_remove_resume_projects_project_resume_projects'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(default='Technical', max_length=100),
        ),
    ]
